version: '3'
services:
  angular-app:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/app
      - /app/node_modules
    depends_on:
      - django-app
  
  django-app:
    build:
      context: ./django-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django-app:/app
    depends_on:
      - mysql
    
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
