name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to django-app directory
        run: cd django-app

      - name: Setup Python 3.11.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: List files in directory
        run: ls
      
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          python manage.py test
      
      - name: Install Railway CLI
        run: |
          curl -sSL https://get.railway.app | sh
      
      - name: Login to Railway
        run: |
          railway login --token $RAILWAY_TOKEN

      - name: Deploy to Railway
        run: |
          railway up
      