name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.11.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1
      
      - name: Install requirements
        run: |
          cd django-app
          pip install -r requirements.txt

      - name: Make migrations
        run: |
          cd django-app
          python manage.py makemigrations

      - name: Apply migrations
        run: |
          cd django-app
          python manage.py migrate
      
      - name: Run tests
        run: |
          cd django-app
          python manage.py test --keepdb --noinput
        
      - name: Install curl
        run: |
          apt-get update -y && apt-get install -y curl

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
      
      - name: Login to Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: |
          railway up
      